# Generated by Django 5.0.4 on 2024-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='item',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_honorario',
            field=models.CharField(choices=[('Honorario Municipal', 'Honorario Municipal'), ('Mixto', 'Mixto'), ('Fondos de Teceros', 'Fondos de Terceros')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='condicion',
            field=models.CharField(choices=[('Contrata', 'Contrata'), ('Planta', 'Planta'), ('Honorarios', 'Honorarios'), ('Codigo del Trabajo', 'Codigo del Trabajo')], max_length=20),
        ),
    ]
