# Generated by Django 5.0.4 on 2024-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trab', '0002_empleado_item_empleado_tipo_honorario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='item',
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cta_administracion_fondos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='etnia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='item_presupuestario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='jefatura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='situacion_discapacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_honorario',
            field=models.CharField(blank=True, choices=[('Honorario Municipal', 'Honorario Municipal'), ('Mixto', 'Mixto'), ('Fondos de Terceros', 'Fondos de Terceros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
