# Generated by Django 5.0.4 on 2024-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trab', '0003_remove_empleado_item_empleado_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Mapuche', 'Mapuche'), ('Aymara', 'Aymara'), ('Rapa Nui', 'Rapa Nui'), ('Quechua', 'Quechua'), ('Colla', 'Colla'), ('Atacameño', 'Atacameño'), ('Diaguita', 'Diaguita'), ('Boricua', 'Boricua'), ('Africana', 'Africana'), ('Otro', 'Otro'), ('No especificada', 'No especificada')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='situacion_discapacidad',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
