# Generated by Django 5.0.4 on 2024-12-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trab', '0004_alter_empleado_etnia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='anios_servicio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='condicion',
            field=models.CharField(choices=[('Contrata', 'Contrata'), ('Planta', 'Planta'), ('Honorarios', 'Honorarios'), ('Codigo del Trabajo', 'Código del Trabajo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='situacion_discapacidad',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
