# Generated by Django 5.0.4 on 2024-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trab', '0005_alter_empleado_anios_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='anios_servicio',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
